# Generated by Django 5.1.2 on 2024-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('not specified', 'Not Specified')], default='not specified', max_length=20, null=True),
        ),
    ]
