# Generated by Django 5.1.2 on 2024-11-08 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in hectares', max_digits=10)),
                ('elevation', models.IntegerField(blank=True, help_text='Elevation in meters', null=True)),
                ('slope', models.CharField(help_text="Slope description, e.g., 'steep', 'gentle'", max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='farm.field')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('harvest_type', models.CharField(blank=True, choices=[('manual', 'Manual'), ('machine', 'Machine')], max_length=50, null=True)),
                ('num_workers', models.IntegerField(blank=True, null=True)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_harvest_date', models.DateTimeField(blank=True, null=True)),
                ('next_harvest_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farm.field')),
            ],
        ),
    ]
