# Generated by Django 5.1.2 on 2024-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_field_alitutude_field_soil_drainage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('harvest', 'Harvest'), ('planting', 'Planting'), ('irrigation', 'Irrigation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='field',
            name='soil_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
