# Generated by Django 5.1.2 on 2024-12-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_activity_activity_type_alter_field_soil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('harvest', 'Harvest'), ('planting', 'Planting'), ('irrigation', 'Irrigation'), ('fertilizing', 'Fertilizing')], max_length=50),
        ),
    ]
