# Generated by Django 5.1.2 on 2024-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='harvest_type',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('harvest', 'Harvest'), ('pruning', 'Pruning'), ('irrigation', 'Irrigation'), ('fertilizing', 'Fertilizing')], max_length=50),
        ),
    ]
