# Generated by Django 5.1.2 on 2024-12-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_remove_activity_harvest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='harvest_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
